version: "3.8"

services:
  nginx:
    env_file:
      - .env
    build:
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - webserv
    volumes:
     - wordpress-vol:/var/www/html

  mariadb:
    env_file:
      - .env
    build:
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - website
    volumes:
      - mariadb-vol:/var/lib/mysql

  wordpress:
    env_file:
      - .env
    build:
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - website
      - webserv
    volumes:
      - wordpress-vol:/var/www/html

networks:
  webserv:
    driver: bridge
  website:
    driver: bridge


volumes:
  wordpress-vol:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER_NAME}/data/wordpress
      o: bind
      type: none
  mariadb-vol:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER_NAME}/data/mariadb
      o: bind
      type: none
