version: "3.3"

services:
  nginx:
    container_name: nginx
    restart: always
    depends_on:
     - wordpress
    env_file:
      - .env
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    networks:
      - webserv
    volumes:
     - /home/${USER_NAME}/data/wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    restart: always
    env_file:
      - .env
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - website
    volumes:
      - /home/${USER_NAME}/data/mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "9000:9000"
    networks:
      - website
      - webserv
    volumes:
      - /home/${USER_NAME}/data/wordpress:/var/www/html

networks:
  webserv:
    driver: bridge
  website:
    driver: bridge