version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data:
